definitions:
  handlers.PingWithParam:
    properties:
      id:
        example: 1
        type: integer
      param2:
        example: yusuf
        type: string
      q:
        example: yusufgg
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Restful API created using gin for koda batch 3
  title: KODA 3 GIN
  version: "1.0"
paths:
  /ping:
    get:
      parameters:
      - description: Header for send id
        in: header
        name: X-Request-ID
        required: true
        type: string
      - description: Header for ..
        in: header
        name: Content-Type
        required: true
        type: string
      responses: {}
      tags:
      - ping
  /ping/:id/:param2:
    get:
      parameters:
      - description: path params for id
        in: path
        name: id
        required: true
        type: integer
      - description: path params for param2
        in: path
        name: param2
        required: true
        type: string
      - description: query for q
        in: query
        name: q
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingWithParam'
      tags:
      - ping
swagger: "2.0"
